// Code generated by protoc-gen-go. DO NOT EDIT.
// source: XTrafficWrapper.proto

package kcwiki_msgtransfer_protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XTrafficProto_ProtoType int32

const (
	XTrafficProto_SYSTEM     XTrafficProto_ProtoType = 0
	XTrafficProto_NON_SYSTEM XTrafficProto_ProtoType = 1
)

var XTrafficProto_ProtoType_name = map[int32]string{
	0: "SYSTEM",
	1: "NON_SYSTEM",
}

var XTrafficProto_ProtoType_value = map[string]int32{
	"SYSTEM":     0,
	"NON_SYSTEM": 1,
}

func (x XTrafficProto_ProtoType) String() string {
	return proto.EnumName(XTrafficProto_ProtoType_name, int32(x))
}

func (XTrafficProto_ProtoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8150bc2b744bee75, []int{0, 0}
}

type XTrafficProto_ProtoCode int32

const (
	XTrafficProto_FAILURE XTrafficProto_ProtoCode = 0
	XTrafficProto_SUCCESS XTrafficProto_ProtoCode = 1
	XTrafficProto_ERROR   XTrafficProto_ProtoCode = 2
	XTrafficProto_UNKNOWN XTrafficProto_ProtoCode = 3
)

var XTrafficProto_ProtoCode_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
	2: "ERROR",
	3: "UNKNOWN",
}

var XTrafficProto_ProtoCode_value = map[string]int32{
	"FAILURE": 0,
	"SUCCESS": 1,
	"ERROR":   2,
	"UNKNOWN": 3,
}

func (x XTrafficProto_ProtoCode) String() string {
	return proto.EnumName(XTrafficProto_ProtoCode_name, int32(x))
}

func (XTrafficProto_ProtoCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8150bc2b744bee75, []int{0, 1}
}

type XTrafficProto struct {
	ProtoType            XTrafficProto_ProtoType `protobuf:"varint,1,opt,name=proto_type,json=protoType,proto3,enum=kcwiki.msgtransfer.protobuf.XTrafficProto_ProtoType" json:"proto_type,omitempty"`
	ProtoCode            XTrafficProto_ProtoCode `protobuf:"varint,2,opt,name=proto_code,json=protoCode,proto3,enum=kcwiki.msgtransfer.protobuf.XTrafficProto_ProtoCode" json:"proto_code,omitempty"`
	ProtoModule          string                  `protobuf:"bytes,3,opt,name=proto_module,json=protoModule,proto3" json:"proto_module,omitempty"`
	ProtoPayload         []byte                  `protobuf:"bytes,4,opt,name=proto_payload,json=protoPayload,proto3" json:"proto_payload,omitempty"`
	ProtoSender          string                  `protobuf:"bytes,5,opt,name=proto_sender,json=protoSender,proto3" json:"proto_sender,omitempty"`
	ProtoRecipient       string                  `protobuf:"bytes,6,opt,name=proto_recipient,json=protoRecipient,proto3" json:"proto_recipient,omitempty"`
	Timestamp            int64                   `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign                 string                  `protobuf:"bytes,8,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *XTrafficProto) Reset()         { *m = XTrafficProto{} }
func (m *XTrafficProto) String() string { return proto.CompactTextString(m) }
func (*XTrafficProto) ProtoMessage()    {}
func (*XTrafficProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8150bc2b744bee75, []int{0}
}

func (m *XTrafficProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XTrafficProto.Unmarshal(m, b)
}
func (m *XTrafficProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XTrafficProto.Marshal(b, m, deterministic)
}
func (m *XTrafficProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XTrafficProto.Merge(m, src)
}
func (m *XTrafficProto) XXX_Size() int {
	return xxx_messageInfo_XTrafficProto.Size(m)
}
func (m *XTrafficProto) XXX_DiscardUnknown() {
	xxx_messageInfo_XTrafficProto.DiscardUnknown(m)
}

var xxx_messageInfo_XTrafficProto proto.InternalMessageInfo

func (m *XTrafficProto) GetProtoType() XTrafficProto_ProtoType {
	if m != nil {
		return m.ProtoType
	}
	return XTrafficProto_SYSTEM
}

func (m *XTrafficProto) GetProtoCode() XTrafficProto_ProtoCode {
	if m != nil {
		return m.ProtoCode
	}
	return XTrafficProto_FAILURE
}

func (m *XTrafficProto) GetProtoModule() string {
	if m != nil {
		return m.ProtoModule
	}
	return ""
}

func (m *XTrafficProto) GetProtoPayload() []byte {
	if m != nil {
		return m.ProtoPayload
	}
	return nil
}

func (m *XTrafficProto) GetProtoSender() string {
	if m != nil {
		return m.ProtoSender
	}
	return ""
}

func (m *XTrafficProto) GetProtoRecipient() string {
	if m != nil {
		return m.ProtoRecipient
	}
	return ""
}

func (m *XTrafficProto) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *XTrafficProto) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func init() {
	proto.RegisterEnum("kcwiki.msgtransfer.protobuf.XTrafficProto_ProtoType", XTrafficProto_ProtoType_name, XTrafficProto_ProtoType_value)
	proto.RegisterEnum("kcwiki.msgtransfer.protobuf.XTrafficProto_ProtoCode", XTrafficProto_ProtoCode_name, XTrafficProto_ProtoCode_value)
	proto.RegisterType((*XTrafficProto)(nil), "kcwiki.msgtransfer.protobuf.XTrafficProto")
}

func init() { proto.RegisterFile("XTrafficWrapper.proto", fileDescriptor_8150bc2b744bee75) }

var fileDescriptor_8150bc2b744bee75 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x4f, 0x6b, 0xea, 0x40,
	0x14, 0xc5, 0x1d, 0xe3, 0xbf, 0x5c, 0x35, 0x2f, 0x0c, 0x3c, 0x18, 0x78, 0x2e, 0xf2, 0x7c, 0x0b,
	0xb3, 0xca, 0xe2, 0xb5, 0xdb, 0x2e, 0xaa, 0xa4, 0x50, 0x5a, 0xa3, 0x4c, 0x14, 0xdb, 0x95, 0xc4,
	0x64, 0x22, 0x83, 0x26, 0x19, 0x26, 0x91, 0xe2, 0x27, 0xee, 0xd7, 0x28, 0x4e, 0x8c, 0xb6, 0x9b,
	0x2e, 0xba, 0x19, 0xce, 0xfd, 0xdd, 0x73, 0x0e, 0xcc, 0x85, 0xdf, 0x2f, 0x0b, 0x19, 0xc4, 0x31,
	0x0f, 0x57, 0x32, 0x10, 0x82, 0x49, 0x47, 0xc8, 0xac, 0xc8, 0xf0, 0x9f, 0x5d, 0xf8, 0xc6, 0x77,
	0xdc, 0x49, 0xf2, 0x6d, 0x21, 0x83, 0x34, 0x8f, 0xab, 0xcd, 0xe6, 0x10, 0x0f, 0xdf, 0x35, 0xe8,
	0x57, 0xb1, 0xb9, 0xb2, 0xfb, 0x00, 0x6a, 0xbb, 0x2e, 0x8e, 0x82, 0x11, 0x64, 0x21, 0xdb, 0xf8,
	0x7f, 0xeb, 0x7c, 0xd3, 0xe1, 0x7c, 0xc9, 0x3b, 0xea, 0x5d, 0x1c, 0x05, 0xa3, 0xba, 0xa8, 0xe4,
	0xb5, 0x34, 0xcc, 0x22, 0x46, 0xea, 0x3f, 0x2b, 0x9d, 0x64, 0x51, 0x55, 0x7a, 0x92, 0xf8, 0x2f,
	0xf4, 0xca, 0xd2, 0x24, 0x8b, 0x0e, 0x7b, 0x46, 0x34, 0x0b, 0xd9, 0x3a, 0xed, 0x2a, 0x36, 0x55,
	0x08, 0xff, 0x83, 0x7e, 0x69, 0x11, 0xc1, 0x71, 0x9f, 0x05, 0x11, 0x69, 0x58, 0xc8, 0xee, 0xd1,
	0x32, 0x37, 0x2f, 0xd9, 0xb5, 0x27, 0x67, 0x69, 0xc4, 0x24, 0x69, 0x7e, 0xea, 0xf1, 0x15, 0xc2,
	0x23, 0xf8, 0x55, 0x5a, 0x24, 0x0b, 0xb9, 0xe0, 0x2c, 0x2d, 0x48, 0x4b, 0xb9, 0x0c, 0x85, 0x69,
	0x45, 0xf1, 0x00, 0xf4, 0x82, 0x27, 0x2c, 0x2f, 0x82, 0x44, 0x90, 0xb6, 0x85, 0x6c, 0x8d, 0x5e,
	0x01, 0xc6, 0xd0, 0xc8, 0xf9, 0x36, 0x25, 0x1d, 0x95, 0x55, 0x7a, 0x38, 0x02, 0xfd, 0x72, 0x32,
	0x0c, 0xd0, 0xf2, 0x5f, 0xfd, 0x85, 0x3b, 0x35, 0x6b, 0xd8, 0x00, 0xf0, 0x66, 0xde, 0xfa, 0x3c,
	0xa3, 0xe1, 0xdd, 0xd9, 0xa8, 0xfe, 0xde, 0x85, 0xf6, 0xc3, 0xfd, 0xe3, 0xf3, 0x92, 0xba, 0x66,
	0xed, 0x34, 0xf8, 0xcb, 0xc9, 0xc4, 0xf5, 0x7d, 0x13, 0x61, 0x1d, 0x9a, 0x2e, 0xa5, 0x33, 0x6a,
	0xd6, 0x4f, 0x7c, 0xe9, 0x3d, 0x79, 0xb3, 0x95, 0x67, 0x6a, 0xe3, 0x01, 0x18, 0x97, 0xe3, 0x2a,
	0x31, 0xee, 0x5c, 0x6e, 0x8c, 0x36, 0x2d, 0x85, 0x6e, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb3,
	0x8b, 0x9a, 0x1e, 0x44, 0x02, 0x00, 0x00,
}
